config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
include KittensHelper
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def create
    Kitten.create(kitten_params)
    flash.notice = "Kitten saved"
    redirect_to root_path
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)
    flash.notice = "Kitten updated"
    redirect_to kitten_path(@kitten)
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash.notice = "Kitten '#{@kitten.name}' has been removed"
    redirect_to kittens_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
  <p>
    <%= f.label :name, "Kitten's name: " %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :age, "Age: " %>
    <%= f.number_field :age %>
  </p>
  <p>
    <%= f.label :cuteness, "Cuteness:" %>
    <%= f.number_field :cuteness %>
  </p>
  <p>
    <%= f.label :softness, "Softness: " %>
    <%= f.number_field :softness %>
  </p> 
  <p><%= f.submit %></p>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>
<%= render partial: 'form' %>
<%= link_to 'Cancel', kitten_path(@kitten) %>
|
<%= link_to 'Delete', kitten_path(@kitten), method: :delete, 
            data: { confirm: "Are you sure you want to delete this kitteh?" } %>

app/views/kittens/index.html.erb
<h1> KITTENS!!!!! </h1>
<% @kittens.each do |kitten| %>
  <div>
    <%= link_to kitten.name, kitten_path(kitten.id) %>
  </div>
<% end %>
<br />
<div> <%= link_to 'Add kitty', new_kitten_path %></div>

app/views/kittens/new.html.erb
<h1>Add new kitten</h1>
<%= render partial: 'form' %>

app/views/kittens/show.html.erb
<h1> <%= @kitten.name %> </h1>
<p> Age: <%= @kitten.age %> </p>
<p> Cuteness: <%= @kitten.cuteness %> </p>
<p> Softness: <%= @kitten.softness %> </p>
<p>
  <%= link_to "Edit", edit_kitten_path(@kitten) %>
  |
  <%= link_to "Delete", kitten_path, method: :delete,
      data: { confirm: "Are you sure you want to delete this fuzzy little kitten?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash.notice %>

<%= yield %>

</body>
</html>